### PR TITLE
Implement the BAOAB Langevin integrator.

### PR DESCRIPTION
**Pull request by Lazemare**
Implement the BAOAB Langevin integrator we discussed in https://github.com/brucefan1983/GPUMD/issues/169.

### CODE REVIEW

**Comment by brucefan1983** [comment]
A general comment:

There are many idential CUDA kernels used in both `ensemble_bao.cu` and `ensemble_lan.cu`. You can consider moving these common kernels to a file `langevin_unitilities.cuh". Then just include this file to both `ensemble_bao.cu` and `ensemble_lan.cu`. See an example for the file `npt_utilities.cuh`, which is included by both `ensemble_npt_ber.cu` and `ensemble_npt_src.cu`. 

Before you do this refactoring, compile the code with `-DDEBUG` and run your example and save the outputs. After you do this refactoring, run the example again and you should get exactly the same outputs.

**Comment by Lazemare** [comment]
Quite reasonable! Let me change the code and make more tests.

**Comment by Lazemare** [comment]
I moved these identical kernels functions to the new `langevin_utilities.cuh` header file. The code is much cleaner now.

**Comment by brucefan1983** [comment]
Great. You can fix my other review comments and particularly the one related to "fixed group".

**Comment by Lazemare** [comment]
I'm sorry, but it seems that I can not find your other comments anywhere. Did I miss something?

**Comment by brucefan1983** [comment]
They are specific comments about some lines of code. Like this:

image

**Comment by brucefan1983** [comment]
In some sense, these comments are "pending", and you are supposed to "close" them with appropriate actions.

**Comment by Lazemare** [comment]
That's weird, your reviews are not showing on my PR page
Screenshot from 2022-04-08 17-32-27

**Comment by brucefan1983** [comment]
you can check "files changed"

**Comment by Lazemare** [comment]
Yeah, I have checked that page, but they are not there too
Screenshot from 2022-04-08 17-42-40

**Comment by brucefan1983** [comment]
Perhaps I need to add you as a collaborator. I just did it. Could you check
again?

**Comment by Lazemare** [comment]
I checked these pages again, but still, I can not find the comments 😢

**Comment by brucefan1983** [comment]
OK, never mind, you can just check this question: 

For operator_B, you considered the case with fixed group, but why not consider it for operator_A as well?

Could this be the reason for the bad temperature control in your NEMD test?

**Comment by Lazemare** [comment]
OK, let me explain the `operator_A` function and the `fixed_group` variable.
The names `operator_A` and `operator_B` come from formula 5 in [1]. The `operator_A` function is corresponding to an operator that advances the positions:

<p align="center">
    
</p>

While the `operator_B` function is corresponding to an operator that advances the velocities:

<p align="center">
    
</p>

(The `O` operator is corresponding to an Ornstein–Uhlenbeck process.)
Using such notations, the standard Velocity-Velet integrator reads as:

<p align="center">
    
</p>

And the BAOAB Langevin integrator reads as:

<p align="center">
    
</p>

To implement these operators, I looked into the `ensemble.cu` file and found that the `fixed_group` variable only affects the velocity advancement:
https://github.com/brucefan1983/GPUMD/blob/103b79ea98ec9d011fc555d1fcb5ea5f23eff1e6/src/integrate/ensemble.cu#L62-L70
As a result, the fixed groups should not affect the `operator_A`, which only does the position advancements. But as you can see, in the BAOAB Langevin thermostat, we do not measure the temperature immediately after the thermostat step (the `O` operator) but wait until the other two operators (one `operator_A` and one `operator_B`) are applied. This surely affects the temperature control but also improves the sampling accuracy in the conformational space. So, I would only advise those who are interested in conformational sampling to use this integrator.

```
[1] Leimkuhler, Benedict, and Charles Matthews. Applied Mathematics Research eXpress 2013.1 (2013): 34-56.
```

**Comment by brucefan1983** [comment]
When a group is fixed, the positions for tha atoms in that group should not change, as in 
```
g_x[i] += vx * time_step;
      g_y[i] += vy * time_step;
      g_z[i] += vz * time_step;
```
where `vx, vy, yz` are set to zero. So you need to consider the fixed group in operator_A as well.

**Comment by brucefan1983** [comment]
So "fixed group" means 
1) positions do not  change (frozen) and
2) velocities are zero (frozen)

The implementation in `ensemble.cu` looks like to considered velocities only, but it also considered position.

**Comment by Lazemare** [comment]
Oh, I see, this is my fault! This must be a bug, I will fix this right now.

**Comment by brucefan1983** [comment]
No worries, just want to know if the NEMD test can become better after this.

**Comment by Lazemare** [comment]
Sure! After this bug is fixed, I will retest the NEMD runs and upload the results here.

**Comment by Lazemare** [comment]
I have run the NEMD test again. But the results are identical. I think this is because the fixed group is not involved in the thermalized region, thus velocities of fixed atoms will not be modified by the `O` operator. And since the first operator applied to the phase vector is `B`, in which we already zeroed the velocities of these atoms, their velocities will keep at zero during the run.

**Comment by brucefan1983** [comment]
This time, seems the temperature difference is correct, but the average temperature is shifted down.

**Comment by Lazemare** [comment]
Yes, the average temperature is lower than the target temperature. I also observed similar phenomena when using the BAOAB Langevin integrator in OpenMM (provided by OpenMMTools).

**Comment by brucefan1983** [comment]
So it is a common problem? Then should we disable this option for NEMD?

**Comment by Lazemare** [comment]
I think this is appropriate. Because NEMD is about the sampling in the momentum space, there will be no good using the BAOAB splitting.

**Comment by brucefan1983** [comment]
You can simply change the input part and removing the option of heat_bao. Other codes can be kept and we might want to test it in the future.

**Comment by Lazemare** [comment]
Okay, I will undo my first commit in this PR.

**Comment by Lazemare** [comment]
Now the `heat_bao` keyword has been disabled.

**Comment by brucefan1983** [comment]
I merged the PR. Thanks for the great contribution!

**Comment by brucefan1983** [comment]
I will update the manual (about `nvt_bao`) upon releasing GPUMD-v3.3.

**Comment by Lazemare** [comment]
This is my pleasure! Thank you very much for your patient guidance!

**Pull request merged**
