### PR TITLE
PIMD-NPT

### PR DESCRIPTION
**Pull request by brucefan1983**
* This PR will implement NPT for PIMD
* Will also add documentation for PIMD, fully resolving issue #79 
* I only made Berendsen barostat working. Perhaps SCR requires nontrivial extension in algorithm.

* Example of isotropic cubic box:
```
potential   Si_Fan_2019.txt
velocity    100

ensemble    pimd 2 100 100 100 -10 100 100
time_step   2
dump_thermo 10
run         2000
```

image

* Example of orthogonal box:
```
potential   Si_Fan_2019.txt
velocity    100

ensemble    pimd 2 100 100 100 1 2 3 100 100 100 100
time_step   2
dump_thermo 10
run         2000
```
image

* Example of triclinic box:
```
potential   Si_Fan_2019.txt
velocity    100

ensemble    pimd 2 100 100 100 1 2 3 4 5 6 100 100 100 100 100 100 100
time_step   2
dump_thermo 10
run         2000
```

image

### CODE REVIEW

**Comment by erhart1** [comment]
Do you need further testing and comparison with QHA?

**Comment by erhart1** [comment]
I was thinking actually about graphite. OK?

**Comment by brucefan1983** [comment]
> aphite. OK?

That is also good. So you do all the calculations? (I don't have resources to do long calculations)

**Comment by brucefan1983** [comment]
@erhart1 Could you check the doc I added to see if there is any missing info about PIMD (I will write about `dump_beads` later)

**Review by erhart1 — COMMENTED** [review]
I find the documentation complete and very helpful.
I made suggestions for some small changes.

**Comment by erhart1** [comment]
## Comparison with QHA

I ran both classical and PIMD simulations using a NEP4 model for diamond, and compared the results with those from an analysis based on the quasi-harmonic approximation (QHA).
The latter should be considered as the reference in this comparison.
The results agree perfectly (see figure below).
The error bars for all data points are (considerably) smaller than the symbol sizes.

Screenshot 2023-05-18 at 10 32 07

**Pull request merged**
