### PR TITLE
calculate some indices correctly for multi-GPU version of NEP

### PR DESCRIPTION
**Pull request by brucefan1983**
* Aim to resolve this issue: #232 
* For the test you sent me, I can run it now after fixing an apparent bug in the code, but I got a CPU memory issue upon the exit of the program. I am not sure if it is due to my testing environment (There are two 2080ti GPUs but one was running another calculation during my test). Could you test the code with the fix here? @AmbroseWong 
* @erhart1 @elindgren You can also test if there is any problem for the multi-GPU version. I have very limited access to multi-GPU computers.

### CODE REVIEW

**Comment by erhart1** [comment]
> * Aim to resolve this issue: [multi-gpu MD with NEP might be broken in the master version #232](https://github.com/brucefan1983/GPUMD/issues/232)
> 
>     * For the test you sent me, I can run it now after fixing an apparent bug in the code, but I got a CPU memory issue upon the exit of the program. I am not sure if it is due to my testing environment (There are two 2080ti GPUs but one was running another calculation during my test). Could you test the code with the fix here? @AmbroseWong
> 
>     * @erhart1 @elindgren You can also test if there is any problem for the multi-GPU version. I have very limited access to multi-GPU computers.

Do you have a specific test case we could run?

**Comment by brucefan1983** [comment]
[multi-gpu-test.zip](https://github.com/brucefan1983/GPUMD/files/9442226/multi-gpu-test.zip)

Here you go. @erhart1

**Comment by erhart1** [comment]
Running on one GPU works
```
started: Mon Aug 29 09:05:28 CEST 2022

***************************************************************
*                 Welcome to use GPUMD                        *
*     (Graphics Processing Units Molecular Dynamics)          *
*                     Version 3.4                             *
*              This is the gpumd executable                   *
***************************************************************


---------------------------------------------------------------
Compiling options:
---------------------------------------------------------------

DEBUG is off: Use different PRNG seeds for different runs.

---------------------------------------------------------------
GPU information:
---------------------------------------------------------------

number of GPUs = 1
Device id:                   0
    Device name:             NVIDIA A100-SXM4-40GB
    Compute capability:      8.0
    Amount of global memory: 39.4434 GB
    Number of SMs:           108
...
---------------------------------------------------------------
Time used = 60.523004 s.
---------------------------------------------------------------


---------------------------------------------------------------
Finished running GPUMD.
---------------------------------------------------------------

finished: Mon Aug 29 09:06:35 CEST 2022
```

**Comment by erhart1** [comment]
Running on two  GPUs does not.
```
started: Mon Aug 29 09:05:29 CEST 2022

***************************************************************
*                 Welcome to use GPUMD                        *
*     (Graphics Processing Units Molecular Dynamics)          *
*                     Version 3.4                             *
*              This is the gpumd executable                   *
***************************************************************


---------------------------------------------------------------
Compiling options:
---------------------------------------------------------------

DEBUG is off: Use different PRNG seeds for different runs.

---------------------------------------------------------------
GPU information:
---------------------------------------------------------------

number of GPUs = 2
Device id:                   0
    Device name:             NVIDIA A100-SXM4-40GB
    Compute capability:      8.0
    Amount of global memory: 39.4434 GB
    Number of SMs:           108
Device id:                   1
    Device name:             NVIDIA A100-SXM4-40GB
    Compute capability:      8.0
    Amount of global memory: 39.4434 GB
    Number of SMs:           108
GPU-0 can access GPU-1.
GPU-1 can access GPU-0.
...
Dump position.
    every 10 steps.
Run 1000 steps.
corrupted double-linked list
/tmp/slurmd/job518119/slurm_script: line 12: 538600 Done                    printf "1\n.\n"
     538601 Aborted                 (core dumped) | ~/repos/GPUMD/src/gpumd
finished: Mon Aug 29 09:05:36 CEST 2022
```

**Comment by brucefan1983** [comment]
For 2 GPUs, is it with or without the fix in this PR?

**Comment by erhart1** [comment]
I ran this on the branch.

**Comment by brucefan1983** [comment]
Ok, then more work is needed...
Thanks.

erhart1 ***@***.***> 于 2022年8月29日周一 10:13写道：

**Comment by brucefan1983** [comment]
I think I have found and fixed some bugs. 

In this test, there is a large vaccumn in the z direction (100 A) and PBC is used for all directions. The number of cells (with a side length of rc_radial/2 = 8A/2 = 4A) is 127x123x25 =390525, which is larger than the number of atoms = 273000. In this case, I forgot to resize an `std::vector` which caused the CPU memory problem.

Actually, it might not be the most efficient to use PBC with a vaccumn layer in GPUMD. So I also tried to add `pbc="t t f"` in `model.xyz` but I got another bug that I have fixed: the atoms are located at about 50 A in the z direction, and I need to change some `if` to `while` to totally move the atoms from a non-zero cell index in the z direction to the 0-index (this is required as there is only one cell in a non-PBC direction in GPUMD).

The test ran fine with two 2080ti GPUs. And you are welcome to double check with your GPUs. @erhart1 @elindgren @AmbroseWong

**Comment by elindgren** [comment]
@brucefan1983 I ran the test, it works well with both 1 and 2 A100s. I also tried with 4 T4s which also works fine. 

```bash 
---------------------------------------------------------------
GPU information:
---------------------------------------------------------------

number of GPUs = 4
Device id:                   0
    Device name:             Tesla T4
    Compute capability:      7.5
    Amount of global memory: 14.615 GB
    Number of SMs:           40
Device id:                   1
    Device name:             Tesla T4
    Compute capability:      7.5
    Amount of global memory: 14.615 GB
    Number of SMs:           40
Device id:                   2
    Device name:             Tesla T4
    Compute capability:      7.5
    Amount of global memory: 14.615 GB
    Number of SMs:           40
Device id:                   3
    Device name:             Tesla T4
    Compute capability:      7.5
    Amount of global memory: 14.615 GB
    Number of SMs:           40
...
---------------------------------------------------------------
Time used for this run = 114.657 second.
Speed of this run = 2.38101e+06 atom*step/second.
---------------------------------------------------------------


---------------------------------------------------------------
Finished executing the commands in run.in.
---------------------------------------------------------------


---------------------------------------------------------------
Time used = 115.090609 s.
---------------------------------------------------------------


---------------------------------------------------------------
Finished running GPUMD.
---------------------------------------------------------------
```

**Comment by AmbroseWong** [comment]
It works well with two a100 here. Thanks a lot! And z-direction PBC does not influence too much run time according to my tests.

**Comment by brucefan1983** [comment]
Seem there is no problem at least for this test now. I will merge this.

**Pull request merged**
