### PR TITLE
Fix nep cpu bugs

### PR DESCRIPTION
**Pull request by brucefan1983**

### CODE REVIEW

**Comment by brucefan1983** [comment]
The bugs occur in some special cases:
1) when descriptor is calculated before force calculation
2) when the second structure has smaller number of atoms the the previous one

**Review by elindgren — APPROVED** [review]
:+1: Looks good to me :)

**Comment by brucefan1983** [comment]
thanks. hope you have not suffered from these bug yet.

**Comment by elindgren** [comment]
> thanks. hope you have not suffered from these bugs yet.

I don't think I've encountered them :sunglasses:

**Pull request merged**
