### PR TITLE
Added first part of documentation in sphinx

### PR DESCRIPTION
**Pull request by erhart1**
This is the first part of the new sphinx based documentation.

### CODE REVIEW

**Comment by brucefan1983** [comment]
Could you see my comments on the files? If not, I will just write here.

**Comment by erhart1** [comment]
Where should I be able to see the comments?

**Comment by brucefan1983** [comment]
for example, I have tried to commented like this:

image

**Comment by brucefan1983** [comment]
Perhaps it's because you are trying to merging from outside. Similar situations have been encountered by others. 

Then we can only communicate by the comments here.

**Comment by erhart1** [comment]
Sorry. The changes in the makefile were local and not meant to be included.
I reverted them in f1b8aec6.

**Comment by erhart1** [comment]
I am actually not merging from outside but created a new branch directly in this repo and then created a PR from that one.

**Comment by brucefan1983** [comment]
ok, then all the files are just new ones. you can tell me when you are done. if you think it is safe to merge I will do it. we can see what happens later.

**Comment by erhart1** [comment]
This should be safe to merge.

**Comment by erhart1** [comment]
It includes all changes we discussed today plus the output files and some smaller adjustments.
I could not get the direct push from GL to work so I manually compiled the changes in a new branch of your original repo.

**Comment by brucefan1983** [comment]
so you mena it's ready to merge?

**Comment by erhart1** [comment]
Yes

**Pull request merged**
