### PR TITLE
SGC and VCSGC MCMD

### PR DESCRIPTION
**Pull request by brucefan1983**
* Add SGC-MCMD and VCSGC-MCMD
* Syntax
```
mc sgc <md_steps> <mc_trials> <T_i> <T_f> <num_species> {species_0 mu_0 species_1 mu_1 ...} [group <grouping_method>  <group_id>]
mc vcsgc <md_steps> <mc_trials> <T_i> <T_f> <num_species> {species_0 phi_0 species_1 phi_1 ...} kappa [group <grouping_method>  <group_id>]
```

* Requirements (otherwise the code will report an error and exit)
  - `num_species` must >=2 and <= 4
  - The listed species must be supported by the NEP model.
  - Must have at least one listed species in the initial model system or specified group. For example, if you list Au and Cu for doing MC, the system/group must have some Au or Cu atoms (or both), otherwise, the MC trail cannot get started.

* Example of SGC:
```
potential nep.txt
velocity 1
time_step 0

ensemble nve
mc sgc 100 100 300 300 2 Au 0 Cu 0  # no chemical potential difference
dump_thermo 100
dump_exyz 100 
run 10000
```

This changes AuCu alloy to pure Cu:

initial:

image

final: 
image

* VCSGC example:
```
potential         nep.txt
velocity           1
time_step        0

ensemble         nve
mc vcsgc         10 100 300 300 2 Au -2 Cu 0  200  # also test kappa= 2000 and 20000
dump_thermo 10
dump_exyz      10
run                 1000
```

9_5N2J%B{ZSJVJCX58_IMXT

The initial system is pure Cu.
Are the results above reasonable? @erhart1 

* More tests: 
I count on you to test if the code works as expected @erhart1

### CODE REVIEW

**Comment by erhart1** [comment]
For the analysis of the results it would be useful to print the atom counts for the species include in the `mc` command to `mcmd.out`. That way one avoids having to write frames with high frequency to extract the concentrations, which is necessary for analyzing the runs.

**Comment by erhart1** [comment]
I am running sweeps atm. I will post the results with more comments, once the runs and the analysis are complete.

**Comment by brucefan1983** [comment]
> For the analysis of the results it would be useful to print the atom counts for the species include in the `mc` command to `mcmd.out`. That way one avoids having to write frames with high frequency to extract the concentrations, which is necessary for analyzing the runs.

Done:
image

**Comment by brucefan1983** [comment]
So I will merge this such that all the recent features are in master.

**Pull request merged**
