### PR TITLE
allow for choosing shear virial weight

### PR DESCRIPTION
**Pull request by brucefan1983**
In most cases, the shear virials/pressures in the training data are much smaller than the diagonal ones and it is might be beneficial to increase the weight for the shear part. Now one can use
```
lambda_shear <value>
```
in `nep.in` to set such a weight. Someone tested that a value of 5 can make the prediction of `C_44` much more accurate in some material.

To solve #295

### CODE REVIEW

**Comment by erhart1** [comment]
Looks good to me.
I would probably rather include more specifically deformed configurations but this seems works for some.
Do you still want to add a page to the documentation?

**Comment by brucefan1983** [comment]
Yes, I will update doc.

**Comment by brucefan1983** [comment]
> Looks good to me. I would probably rather include more specifically deformed configurations but this seems works for some. Do you still want to add a page to the documentation?

In some cases it is even insufficient to include specifically deformed configurations according to tests by Zhiqiang (I think he has contact you for entory maximization). The problem is the shear virials/moduli are much smaller than diagonal ones in some materials (one order of magnitude smaller).

**Comment by brucefan1983** [comment]
I messed up by doing something accidently in master...
perhaps need to start this PR over

**Comment by brucefan1983** [comment]
I fixed the conflict and it is ready to merge to master. 

documentation has been directly committed to master.

**Pull request merged**
