### PR TITLE
Implement the interface to the PLUMED plugin.

### PR DESCRIPTION
**Pull request by Lazemare**

### CODE REVIEW

**Comment by brucefan1983** [comment]
`std::vector` can be accessed in this way:
```
cpu_b_vector[0]
```
which is simpler than 
```
cpu_b_vector.data()[0]
```

**Comment by brucefan1983** [comment]
Move these from header file to implementation file:
```
#define E_C 1.602176634E-19 // Elementary charge
#define N_A 6.0221367E23    // Avogadro constant

const double ENERGY_UNIT_CONVERSION = N_A * E_C / 1000; // from eV to kJ/mol
```

**Comment by Lazemare** [comment]
All done 👌

**Comment by Lazemare** [comment]
Thank you! It's my pleasure 😊

**Comment by brucefan1983** [comment]
Would you like to prepare a tutorial with a good example for using GPUMD with PLUMED? If the relevant output files are not large, the tutorial can all the inputs/outputs can be put into, say `examples/xxx_potentials/plumed/`.

**Comment by Lazemare** [comment]
Sure! I will make some examples to briefly explain the usage of PLUMED in GPUMD. Also there will be a documentation to talk about the installation and the performance issues.

**Comment by brucefan1983** [comment]
Hello, do you have time to wirte documentation for the PLUMED interface?

**Pull request merged**
